import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { getMigrations } from "better-auth/db/migration";
import { randomBytes } from "node:crypto";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createCloudflareIdentity, D1_POLICY_SCHEMA } from "../src/cloudflare.js";

// Generates schema from the pinned maintained library using an empty, disposable
// native D1 runtime. No production connection or credentials are loaded.
const runtime = new Miniflare(convertV4MiniflareOptions({ modules: true,
  script: "export default { fetch() { return new Response(null, {status:404}); } };",
  compatibilityDate: "2026-10-09", d1Databases: ["IDENTITY_DB"], telemetry: { enabled: false } }));
try {
  const db = await runtime.getD1Database("IDENTITY_DB");
  const { auth } = createCloudflareIdentity({ IDENTITY_DB: db, PRIVATE_ACCESS: "closed",
    BETTER_AUTH_SECRET: randomBytes(32).toString("hex") }, async () => { throw new Error("No mail in schema generator"); });
  const migration = await getMigrations(auth.options);
  const generated = "-- Generated by Better Auth 1.7.7; do not hand-edit auth tables.\n" +
    await migration.compileMigrations() + "\n\n" + D1_POLICY_SCHEMA.join(";\n\n") + ";\n";
  const directory = new URL("../../deploy/cloudflare/migrations/", import.meta.url);
  const target = new URL("0001_identity.sql", directory);
  if (process.argv.includes("--check")) {
    if (await readFile(target, "utf8") !== generated) throw new Error("D1 schema differs from the shared auth configuration");
    console.log("D1 generated schema matches shared authentication policy");
  } else {
    await mkdir(directory, { recursive: true });
    await writeFile(target, generated);
    console.log("Generated D1 identity schema; no credentials or user data included");
  }
} finally { await runtime.dispose(); }
