-- Generated by Better Auth 1.7.7; do not hand-edit auth tables.
create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null, "twoFactorEnabled" integer);

create table "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "activeOrganizationId" text);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

create table "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" date not null, "metadata" text);

create table "member" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "userId" text not null references "user" ("id") on delete cascade, "role" text not null, "createdAt" date not null);

create table "invitation" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" date not null, "createdAt" date not null, "inviterId" text not null references "user" ("id") on delete cascade);

create table "twoFactor" ("id" text not null primary key, "secret" text not null, "backupCodes" text not null, "userId" text not null references "user" ("id") on delete cascade, "verified" integer, "failedVerificationCount" integer, "lockedUntil" date);

create table "apikey" ("id" text not null primary key, "configId" text not null, "name" text, "start" text, "referenceId" text not null, "prefix" text, "key" text not null, "refillInterval" integer, "refillAmount" integer, "lastRefillAt" date, "enabled" integer, "rateLimitEnabled" integer, "rateLimitTimeWindow" integer, "rateLimitMax" integer, "requestCount" integer, "remaining" integer, "lastRequest" date, "expiresAt" date, "createdAt" date not null, "updatedAt" date not null, "permissions" text, "metadata" text);

create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create index "member_organizationId_idx" on "member" ("organizationId");

create index "member_userId_idx" on "member" ("userId");

create index "invitation_organizationId_idx" on "invitation" ("organizationId");

create index "invitation_email_idx" on "invitation" ("email");

create index "twoFactor_secret_idx" on "twoFactor" ("secret");

create index "twoFactor_userId_idx" on "twoFactor" ("userId");

create index "apikey_configId_idx" on "apikey" ("configId");

create index "apikey_referenceId_idx" on "apikey" ("referenceId");

create index "apikey_key_idx" on "apikey" ("key");

CREATE TABLE IF NOT EXISTS demandlab_membership_status (
    company_id TEXT NOT NULL, user_id TEXT NOT NULL,
    suspended INTEGER NOT NULL DEFAULT 0 CHECK(suspended IN (0,1)),
    PRIMARY KEY(company_id,user_id));

CREATE TABLE IF NOT EXISTS demandlab_key_bindings (
    key_id TEXT PRIMARY KEY, company_id TEXT NOT NULL, owner_id TEXT NOT NULL,
    service_role TEXT CHECK(service_role IN ('planner','viewer')),
    revoked INTEGER NOT NULL DEFAULT 0 CHECK(revoked IN (0,1)));

CREATE TABLE IF NOT EXISTS demandlab_audit (
    id INTEGER PRIMARY KEY AUTOINCREMENT, company_id TEXT NOT NULL, actor_id TEXT NOT NULL,
    event TEXT NOT NULL, resource_id TEXT, created_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS demandlab_session_mfa (
    session_id TEXT PRIMARY KEY REFERENCES "session"(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    verified_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS demandlab_session_company (
    session_id TEXT NOT NULL REFERENCES "session"(id) ON DELETE CASCADE,
    company_id TEXT NOT NULL, PRIMARY KEY(session_id,company_id));

CREATE INDEX IF NOT EXISTS demandlab_key_company ON demandlab_key_bindings(company_id,owner_id);

CREATE INDEX IF NOT EXISTS demandlab_audit_company ON demandlab_audit(company_id,created_at);
